<div class="container-fluid mt-3">
    <div class="row">
        <div class="col-md-10">
            <p>
                <h2>
                    <i class="material-icons" style="font-size: 34px">build</i>
                    <?php echo $this->getPageTitle(); ?>
                </h2>
            </p>
        </div>
        <div class="col-md-2 text-right mt-3">
            <button type="button" class="btn btn-outline-primary" onclick="history.go(-1)" title="Voltar">
                <i class="material-icons" style="font-size: 18px;">arrow_back</i>
            </button>
            <button data-toggle="collapse" data-target="#novaManutencao" class="btn btn-outline-primary" title="Registrar Nova">
                <i class="material-icons" style="font-size: 18px;">add</i>
            </button>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <form id="novaManutencao" class="form-horizontal collapse <?php echo $this->view->show ?>" action="<?php echo BASE_URL ?>/gerenciamento/ativo/manutencao/salvar" method="post" accept-charset="utf-8">
                <input name="action" type="hidden" value="<?php echo $this->view->action ?>">
                <input name="id" type="hidden" value="<?php echo $this->view->manutencao->id ?>">
                <input name="ativo_id" type="hidden" value="<?php echo $this->view->ativo->id ?>">

                <div class="form-group">
                    <label>Data Inicial</label>
                    <input name="datainicio" type="datetime-local" class="form-control"
                           value="<?php
                                    if (isset($this->view->manutencao->datainicio)) echo date('Y-m-d\TH:i:s',strtotime($this->view->manutencao->datainicio));
                                    else echo date('Y-m-d\TH:i:s');
                                ?>">
                </div>
                <div class="form-group">
                    <label>Data Final</label>
                    <input name="datafim" type="datetime-local" class="form-control"
                           value="<?php
                           if (isset($this->view->manutencao->datafim)) echo date('Y-m-d\TH:i:s',strtotime($this->view->manutencao->datafim));
                           else echo date('Y-m-d\TH:i:s', strtotime("tomorrow"));
                           ?>">
                </div>
                <div class="form-group">
                    <label>Descrição</label>
                    <textarea name="descricao" class="form-control"><?php echo $this->view->manutencao->descricao ?></textarea>
                </div>
                <div class="form-group">
                    <label>Status</label>
                    <select name="status" class="form-control">
                        <option value="0" <?php echo $this->view->manutencao->status == 0 ? "selected" : ""?>>Em Manutenção</option>
                        <option value="1" <?php echo $this->view->manutencao->status == 1 ? "selected" : ""?>>Em Espera</option>
                        <option value="2" <?php echo $this->view->manutencao->status == 2 ? "selected" : ""?>>Em Teste</option>
                        <option value="3" <?php echo $this->view->manutencao->status == 3 ? "selected" : ""?>>Falha</option>
                        <option value="4" <?php echo $this->view->manutencao->status == 4 ? "selected" : ""?>>Completa</option>
                    </select>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-outline-success">
                        <i class="material-icons" style="font-size: 18px;">check</i>
                        Salvar
                    </button>
                    <button class="btn btn-outline-warning" data-toggle="collapse" data-target="#novaManutencao">
                        <i class="material-icons" style="font-size: 18px;">clear</i>
                        Cancelar
                    </button>
                </div>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <p>
                <h2>
                    <i class="material-icons" style="font-size: 34px">history</i>
                    Histórico
                </h2>
            </p>
        </div>
    </div>
    <?php foreach($this->view->manutencoes as $manutencao){?>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header bg-primary text-white clicavel" data-toggle="collapse" href="#manutencao<?php echo $manutencao->id?>">
                    <div class="row">
                        <div class="col-md-10">
                            Código #<?php  printf("%05d", $manutencao->id)?>
                        </div>
                        <div class="col-md-2 text-right">
                            <i class="material-icons" style="font-size: 18px;">keyboard_arrow_down</i>
                        </div>
                    </div>
                </div>
                <div id="manutencao<?php echo $manutencao->id?>" class="card-body collapse">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="label-default"> Data Inicial: <?php echo date('d/m/Y à\s H:i',strtotime($manutencao->datainicio)) ?></div>
                            <div class="label-default"> Data Final: <?php echo date('d/m/Y à\s H:i',strtotime($manutencao->datafim)) ?></div>
                            <div class="label-default"> Descrição: <?php echo $manutencao->descricao ?></div>
                            <div class="label-default"> Status:
                                <?php
                                    echo $manutencao->status == 0 ? "Em Manutenção" : "";
                                    echo $manutencao->status == 1 ? "Em Espera" : "";
                                    echo $manutencao->status == 2 ? "Em Teste" : "";
                                    echo $manutencao->status == 3 ? "Falha" : "";
                                    echo $manutencao->status == 4 ? "Completa" : "";
                                ?>
                            </div>
                        </div>
                        <div class="col-md-4 text-right">
                            <button class="btn btn-outline-info" onclick="location='<?php echo BASE_URL ?>/gerenciamento/ativo/manutencao/editar/<?php echo $manutencao->id?>'" title="Editar">
                                <i class="material-icons" style ="font-size: 18px;">edit</i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
    <?php }?>
</div>

<?php
    if (isset($this->success))
        $this->setView('modal/success');
    else if (isset($this->errors))
        $this->setView('modal/error');