<div class="container-fluid">
    <br>
    <div class="row">
        <div class="col-md-12">
            <h1>
                <i class="material-icons" style="font-size: 38px">donut_large</i>
                <?php echo $this->view->nome; ?>
            </h1>
        </div>
    </div>
    <br>
</div>

<!--<GERENCIAMENTO>-->
<div class="container-fluid box">
    <div class="row">
        <div class="col-md-12">
            <h2 class="">
                <i class="material-icons" style="font-size: 34px">view_quilt</i>
                Gerenciamento
            </h2>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-md-6">
            <div class="card bg-primary">
                <div class="card-header text-white">
                    <div class="row">
                        <div class="col-md-8">
                            <h4>
                                <i class="material-icons" style="font-size: 28px;">devices</i>
                                Ativos
                                <span class="badge badge-pill badge-light text-primary"><?php echo $this->view->contador->ativos ?></span>
                            </h4>
                        </div>
                        <div class="col-md-4 text-right">
                            <span class="badge badge-pill badge-light text-primary clicavel" title="Ir para Ativos" onclick="location='gerenciamento/ativo'">
                                <i class="material-icons" style="font-size: 14px">call_made</i>
                            </span>
                        </div>
                    </div>
                </div>
                <div id="body-ativo" class="card-body collapse  bg-white">
                    <h5>
                        Monitorados:
                        <?php echo $this->view->contador->ativos->monitorados; ?>
                    </h5>
                    <br>
                    <h5>
                        Não Monitorados:
                        <?php echo $this->view->contador->ativos->naoMonitorados; ?>
                    </h5>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card bg-info text-white clicavel">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-8">
                            <h4>
                                <i class="material-icons" style="font-size: 28px;">memory</i>
                                Componentes
                                <span class="badge badge-pill badge-light text-info"><?php echo $this->view->contador->componentes ?></span>
                            </h4>
                        </div>
                        <div class="col-md-4 text-right">
                            <span class="badge badge-pill badge-light text-info clicavel" title="Ir para Componentes" onclick="location='gerenciamento/componente'">
                                <i class="material-icons" style="font-size: 14px">call_made</i>
                            </span>
                        </div>
                    </div>
                </div>
                <div id="body-componente" class="card-body collapse  bg-white"></div>
            </div>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-md-6">
            <div class="card bg-success text-white clicavel">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-8">
                            <h4>
                                <i class="material-icons" style="font-size: 28px;">keyboard</i>
                                Equipamentos
                                <span class="badge badge-pill badge-light text-success"><?php echo $this->view->contador->equipamentos ?></span>
                            </h4>
                        </div>
                        <div class="col-md-4 text-right">
                            <span class="badge badge-pill badge-light text-success clicavel" title="Ir para Equipamentos" onclick="location='gerenciamento/equipamento'">
                                <i class="material-icons" style="font-size: 14px">call_made</i>
                            </span>
                        </div>
                    </div>
                </div>
                <div id="body-equipamento" class="card-body collapse  bg-white"></div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card bg-danger text-white clicavel">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-8">
                            <h4>
                                <i class="material-icons" style="font-size: 28px;">copyright</i>
                                Licenças
                                <span class="badge badge-pill badge-light text-danger"><?php echo $this->view->contador->licencas ?></span>
                            </h4>
                        </div>
                        <div class="col-md-4 text-right">
                            <span class="badge badge-pill badge-light text-danger clicavel" title="Ir para Licenças" onclick="location='gerenciamento/licenca'">
                                <i class="material-icons" style="font-size: 14px">call_made</i>
                            </span>
                        </div>
                    </div>
                </div>
                <div id="body-licenca" class="card-body collapse  bg-white"></div>
            </div>
        </div>
    </div>
    <br>
</div>
<!--</GERENCIAMENTO>-->
<br>
<!--<MONITORAMENTO>-->
<div class="container-fluid box">
    <div class="row">
        <div class="col-md-12">
            <h2 class="">
                <i class="material-icons" style="font-size: 34px">slow_motion_video</i>
                Monitoramento
            </h2>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-md-6">
            <div class="card bg-primary">
                <div class="card-header text-white">
                    <div class="row">
                        <div class="col-md-10">
                            <h4>
                                <i class="material-icons" style="font-size: 28px;">public</i>
                                Velocidade da Internet
                            </h4>
                            <span class="badge badge-pill badge-light text-primary" title="download"><?php echo $this->view->contador->internet->download ?>Mbit/s</span>
                                <span class="badge badge-pill badge-light text-primary" title="upload"><?php echo $this->view->contador->internet->upload ?>Mbit/s</span>
                        </div>
                        <div class="col-md-2 text-right">
                            <span class="badge badge-pill badge-light text-primary clicavel" title="Ir para Ativos" onclick="location='monitoramento/internet'">
                                <i class="material-icons" style="font-size: 14px">call_made</i>
                            </span>
                        </div>
                    </div>
                </div>
                <div id="body-ativo" class="card-body collapse  bg-white"></div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card bg-info text-white">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-8">
                            <h4>
                                <i class="material-icons" style="font-size: 28px;">drafts</i>
                                IMCP (Ping)
                                <span class="badge badge-pill badge-light text-info">
                                    <i class="material-icons text-success" title="Acessíveis">check</i>
                                    <?php echo $this->view->contador->ping->acessiveis ?>
                                </span>
                                <span class="badge badge-pill badge-light text-info">
                                    <i class="material-icons text-danger" title="Inacessíveis">clear</i>
                                    <?php echo $this->view->contador->ping->inacessiveis ?>
                                </span>
                            </h4>
                        </div>
                        <div class="col-md-4 text-right">
                            <span class="badge badge-pill badge-light text-info clicavel" title="Ir para Componentes" onclick="location='monitoramento/icmp'">
                                <i class="material-icons" style="font-size: 14px">call_made</i>
                            </span>
                        </div>
                    </div>
                </div>
                <div id="body-componente" class="card-body collapse  bg-white"></div>
            </div>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-md-6">
            <div class="card bg-success text-white">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-8">
                            <h4>
                                <i class="material-icons" style="font-size: 28px;">http</i>
                                HTTP/HTTPS
                                <span class="badge badge-pill badge-light text-info">
                                    <i class="material-icons text-success" title="Acessíveis">check</i>
                                    <?php echo $this->view->contador->http->acessiveis ?>
                                </span>
                                <span class="badge badge-pill badge-light text-info">
                                    <i class="material-icons text-danger" title="Inacessíveis">clear</i>
                                    <?php echo $this->view->contador->http->inacessiveis ?>
                                </span>
                            </h4>
                        </div>
                        <div class="col-md-4 text-right">
                            <span class="badge badge-pill badge-light text-success clicavel" title="Ir para Equipamentos" onclick="location='monitoramento/http'">
                                <i class="material-icons" style="font-size: 14px">call_made</i>
                            </span>
                        </div>
                    </div>
                </div>
                <div id="body-equipamento" class="card-body collapse  bg-white"></div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card bg-danger text-white">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-8">
                            <h4>
                                <i class="material-icons" style="font-size: 28px;">share</i>
                                SNMP
                                <span class="badge badge-pill badge-light text-danger"><?php echo $this->view->contador->licencas ?></span>
                            </h4>
                        </div>
                        <div class="col-md-4 text-right">
                            <span class="badge badge-pill badge-light text-danger clicavel" title="Ir para Licenças" onclick="location='monitoramento/snmp'">
                                <i class="material-icons" style="font-size: 14px">call_made</i>
                            </span>
                        </div>
                    </div>
                </div>
                <div id="body-licenca" class="card-body collapse  bg-white"></div>
            </div>
        </div>
    </div>
    <br>
</div>
<!--</MONITORAMENTO>-->