<div class="container-fluid mt-1">

    <form class="form-horizontal" action="/gerenciamento/ativo/salvar" method="post" accept-charset="utf-8">

        <div class="card card-inverse">

            <div class="card-header">

                <div class="row">
                    <h3 class="col-md-10">
                        <i class="material-icons" style="font-size: 28px">devices</i>
                        Novo Ativo
                    </h3>

                    <div class="col-md-2 text-right">
                        <button type="submit" class="btn btn-success">
                            <i class="material-icons">done</i>
                            Gravar
                        </button>

                        <button type="button" class="btn btn-danger" onclick="history.go(-1)">
                            <i class="material-icons">clear</i>
                            Cancelar
                        </button>
                    </div>
                </div>
            </div>

            <div class="card-body">

                <div class="form-group">
                    <label>Número de Patrimônio</label>
                    <input name="nrpatrimonio" type="text" class="form-control" placeholder="Identificador">
                </div>

                <div class="form-group">
                    <label>Nome</label>
                    <input name="nome" type="text" class="form-control" placeholder="Nome visível do ativo">
                </div>

                <div class="form-group">
                    <label>Tag</label>
                    <input name="tag" type="text" class="form-control" placeholder="Tag do modelo">
                </div>

                <div class="form-group">
                    <label>Descrição</label>
                    <textarea name="descricao" class="form-control">
                    </textarea>
                </div>

                <div class="form-group">
                    <label>Data de Compra</label>
                    <input name="datacompra" type="date" class="form-control">
                </div>

                <div class="form-group">

                    <label></label>

                    <label class="custom-control custom-checkbox">
                        <input name="monitorar" value="1" type="checkbox" class="custom-control-input">
                        <span class="custom-control-indicator"></span>
                        <span class="custom-control-description">Monitorar?</span>
                    </label>

                </div>

                <div class="form-group">
                    <label>Categoria</label>
                    <select  multiple class="form-control" name="categoria_ativo_id">
                        <option>1</option>
                        <option>2</option>
                    </select>
                </div>

                <div class="form-group">
                    <label>Sistema Operacional</label>
                    <select  multiple class="form-control" name="so_id">
                    </select>
                </div>

                <div class="form-group">
                    <label>Modelo</label>
                    <select  multiple class="form-control" name="modelo_id">
                    </select>
                </div>

                <div class="form-group">
                    <label>Usuário</label>
                    <select  multiple class="form-control" name="usuario_id">
                    </select>
                </div>

            </div>

        </div>

    </form>

</div>