<div class="container-fluid mt-1">

    <form class="form-horizontal" action="/gerenciamento/ativo/salvar" method="post" accept-charset="utf-8">
        <input name="action" type="hidden" value="<?php echo $this->view->action ?>">
        <input name="ativo_id" type="hidden" value="<?php echo $this->view->ativo->ativo_id ?>">

        <div class="card card-inverse">

            <div class="card-header">

                <div class="row">
                    <h3 class="col-md-10">
                        <i class="material-icons" style="font-size: 28px">devices</i>
                        <?php echo $this->getPageTitle(); ?>
                    </h3>

                    <div class="col-md-2 text-right">
                        <button type="submit" class="btn btn-success">
                            <i class="material-icons" style="font-size: 18px;">done</i>
                            Gravar
                        </button>

                        <button type="button" class="btn btn-danger" onclick="history.go(-1)">
                            <i class="material-icons" style="font-size: 18px;">clear</i>
                            Cancelar
                        </button>
                    </div>
                </div>
            </div>

            <div class="card-body">

                <div class="form-group">
                    <label>Número de Patrimônio</label>
                    <input name="nrpatrimonio" type="text" class="form-control" placeholder="Identificador"
                           value="<?php echo $this->view->ativo->nrpatrimonio ?>">
                </div>

                <div class="form-group">
                    <label>Nome</label>
                    <input name="nome" type="text" class="form-control" placeholder="Nome visível do ativo"
                           value="<?php echo $this->view->ativo->nome?>">
                </div>

                <div class="form-group">
                    <label>Tag</label>
                    <input name="tag" type="text" class="form-control" placeholder="Tag do modelo"
                           value="<?php echo $this->view->ativo->tag ?>">
                </div>

                <div class="form-group">
                    <label>Descrição</label>
                    <textarea name="descricao" class="form-control"><?php echo $this->view->ativo->descricao ?></textarea>
                </div>

                <div class="form-group">
                    <label>Data de Compra</label>
                    <input name="datacompra" type="date" class="form-control"
                           value="<?php echo $this->view->ativo->datacompra ?>">
                </div>

                <div class="form-group">

                    <label></label>

                    <label class="custom-control custom-checkbox">
                        <input name="monitorar" type="checkbox" class="custom-control-input" <?php echo $this->view->ativo->monitorar ?>>
                        <span class="custom-control-indicator"></span>
                        <span class="custom-control-description">Monitorar?</span>
                    </label>

                </div>

                <div class="form-group">
                    <label>Categoria</label>
                    <select  multiple class="form-control" name="categoria_ativo_id">

                        <?php

                        $selected = "";

                        foreach ($this->view->categoria_ativo as $categoria) {
                            if (isset($this->view->ativo->categoria_ativo_id) && ($categoria->categoria_ativo_id == $this->view->ativo->categoria_ativo_id)) {
                                $selected = "selected";
                            }
                            else{
                                $selected = "";
                            }
                            ?>
                            <option <?php echo $selected ?> value="<?php echo $categoria->categoria_ativo_id?>">
                                <?php echo $categoria->nome ?>
                            </option>

                        <?php } ?>

                    </select>
                </div>

                <div class="form-group">
                    <label>Sistema Operacional</label>
                    <select  multiple class="form-control" name="so_id" value="<?php echo $this->view->ativo->so_id ?>">

                        <?php

                        $selected = "";

                        foreach ($this->view->so as $so) {
                            if (isset($this->view->ativo->so_id) && ($so->so_id == $this->view->ativo->so_id)) {
                                $selected = "selected";
                            }
                            else{
                                $selected = "";
                            }
                            ?>
                            <option <?php echo $selected ?> value="<?php echo $so->so_id?>">
                                <?php echo $so->nome . " | Versão: " . $so->versao?>
                            </option>

                        <?php } ?>

                    </select>
                </div>

                <div class="form-group">
                    <label>Modelo</label>
                    <select  multiple class="form-control" name="modelo_id" value="<?php echo $this->view->ativo->modelo_id ?>"s>
                    </select>
                </div>

                <div class="form-group">
                    <label>Usuário</label>
                    <select  multiple class="form-control" name="usuario_id" value="<?php echo $this->view->ativo->usuario_id ?>">
                    </select>
                </div>

            </div>

        </div>

    </form>

</div>