<div class="container-fluid mt-1">

    <form class="form-horizontal" action="/gerenciamento/ativo/salvar" method="post" accept-charset="utf-8">
        <input name="action" type="hidden" value="<?php echo $this->view->action ?>">
        <input name="id" type="hidden" value="<?php echo $this->view->ativo->id ?>">

        <div class="card card-inverse">

            <div class="card-header">

                <div class="row">
                    <h3 class="col-md-10">
                        <i class="material-icons" style="font-size: 28px">devices</i>
                        <?php echo $this->getPageTitle(); ?>
                    </h3>

                    <div class="col-md-2 text-right">
                        <button type="submit" class="btn btn-success">
                            <i class="material-icons" style="font-size: 18px;">done</i>
                            Gravar
                        </button>

                        <button type="button" class="btn btn-danger" onclick="location='/gerenciamento/ativo'">
                            <i class="material-icons" style="font-size: 18px;">clear</i>
                            Cancelar
                        </button>
                    </div>
                </div>
            </div>

            <div class="card-body">

                <div class="form-group">
                    <label>Número de Patrimônio</label>
                    <input name="nrpatrimonio" class="form-control" placeholder="Identificador"
                           value="<?php
                                    echo isset($this->inputs['nrpatrimonio']) ? $this->inputs['nrpatrimonio'] : $this->view->ativo->nrpatrimonio
                                ?>">
                    <?php if (isset($this->errors['nrpatrimonio'])) { ?>
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span>&times;</span>
                            </button>
                            <?php echo $this->errors['nrpatrimonio'];?>
                        </div>
                    <?php } ?>
                </div>

                <div class="form-group">
                    <label>Nome</label>
                    <input name="nome" class="form-control" placeholder="Nome visível do ativo"
                           value="<?php
                           echo isset($this->inputs['nome']) ? $this->inputs['nome'] : $this->view->ativo->nome
                           ?>">
                    <?php if (isset($this->errors['nome'])) { ?>
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span>&times;</span>
                            </button>
                            <?php echo $this->errors['nome'];?>
                        </div>
                    <?php } ?>
                </div>

                <div class="form-group">
                    <label>Tag</label>
                    <input name="tag" class="form-control" placeholder="Tag do modelo"
                           value="<?php
                           echo isset($this->inputs['tag']) ? $this->inputs['tag'] : $this->view->ativo->tag
                           ?>">
                    <?php if (isset($this->errors['tag'])) { ?>
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span>&times;</span>
                            </button>
                            <?php echo $this->errors['tag'];?>
                        </div>
                    <?php } ?>
                </div>

                <div class="form-group">
                    <label>Descrição</label>
                    <textarea name="descricao" class="form-control"><?php
                            echo isset($this->inputs['descricao']) ? $this->inputs['descricao'] : $this->view->ativo->descricao
                        ?></textarea>
                        <?php if (isset($this->errors['descricao'])) { ?>
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span>&times;</span>
                            </button>
                                <?php echo $this->errors['descricao'];?>
                        </div>
                        <?php } ?>
                </div>

                <div class="form-group">
                    <label>Data de Compra</label>
                    <input name="datacompra" type="date" class="form-control"
                           value="<?php
                           echo isset($this->inputs['datacompra']) ? $this->inputs['datacompra'] : $this->view->ativo->datacompra
                           ?>">
                    <?php if (isset($this->errors['datacompra'])) { ?>
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span>&times;</span>
                            </button>
                            <?php echo $this->errors['datacompra'];?>
                        </div>
                    <?php } ?>
                </div>

                <div class="form-group">

                    <label class="custom-control custom-checkbox">
                        <input name="monitorar" type="checkbox" class="custom-control-input" <?php echo $this->view->ativo->monitorar ?>>
                        <span class="custom-control-indicator"></span>
                        <span class="custom-control-description">Monitorar?</span>
                    </label>

                </div>

                <div class="form-group">
                    <label>Categoria</label>
                    <select  class="form-control" name="categoria_ativo_id">

                        <?php

                        $selected = "";

                        foreach ($this->view->categorias as $categoria) {
                            if (isset($this->view->ativo->categoria_ativo_id) && ($categoria->id == $this->view->ativo->categoria_ativo_id)) {
                                $selected = "selected";
                            }
                            else{
                                $selected = "";
                            }
                            ?>
                            <option <?php echo $selected ?> value="<?php echo $categoria->id?>">
                                <?php echo $categoria->nome ?>
                            </option>

                        <?php } ?>

                    </select>
                </div>

                <div class="form-group">
                    <label>Sistema Operacional</label>
                    <select  class="form-control" name="so_id" value="<?php echo $this->view->ativo->so_id ?>">
                        <option>Nenhum</option>
                        <?php

                        $selected = "";

                        foreach ($this->view->sos as $so) {
                            if (isset($this->view->ativo->so_id) && ($so->id == $this->view->ativo->so_id)) {
                                $selected = "selected";
                            }
                            else{
                                $selected = "";
                            }
                            ?>
                            <option <?php echo $selected ?> value="<?php echo $so->id?>">
                                <?php echo $so->nome . " | Versão: " . $so->versao?>
                            </option>

                        <?php } ?>

                    </select>
                </div>

                <div class="form-group">
                    <label>Serial do Sistema Operacional</label>
                    <input class="form-control" name="serial" value="<?php echo $this->view->ativo->serial ?>">
                </div>

                <div class="form-group">
                    <label>Modelo</label>
                    <select class="form-control" name="modelo_id" value="<?php echo $this->view->ativo->modelo_id ?>">
                        <option>Nenhum</option>
                        <?php

                        $selected = "";

                        foreach ($this->view->modelos as $modelo) {
                            if (isset($this->view->ativo->modelo_id) && ($modelo->id == $this->view->ativo->modelo_id)) {
                                $selected = "selected";
                            }
                            else{
                                $selected = "";
                            }
                            ?>
                            <option <?php echo $selected ?> value="<?php echo $modelo->id?>">
                                <?php echo $modelo->nome?>
                            </option>

                        <?php } ?>

                    </select>
                </div>

                <div class="form-group">
                    <label>Usuário</label>
                    <select  class="form-control" name="usuario_id" value="<?php echo $this->view->ativo->usuario_id ?>">
                        <option>Nenhum</option>
                        <?php

                        $selected = "";

                        foreach ($this->view->usuarios as $usuario) {
                            if (isset($this->view->ativo->usuario_id) && ($usuario->id == $this->view->ativo->usuario_id)) {
                                $selected = "selected";
                            }
                            else{
                                $selected = "";
                            }
                            ?>
                            <option <?php echo $selected ?> value="<?php echo $usuario->id?>">
                                <?php echo $usuario->name?>
                            </option>

                        <?php } ?>
                    </select>
                </div>

            </div>

        </div>

    </form>

</div>