<div class="container-fluid">

    <div class="row">

        <div class="col-md-4">
            <p>
                <h1>
                    <i class="material-icons" style="font-size: 38px">devices</i>
                    <?php $this->getPageTitle(); ?>
                </h1>
            </p>
        </div>

        <div class="col-md-8 text-right mt-3">
            <button type="button" class="btn btn-outline-primary" onclick="location='ativo/adicionar'">
                <i class="material-icons" style="font-size: 18px;">add</i>
                Novo Ativo
            </button>
            <button type="button" class="btn btn-outline-primary" onclick="location='categoriaativo/adicionar'">
                <i class="material-icons" style="font-size: 18px;">add_to_queue</i>
                Nova Categoria
            </button>
        </div>

    </div>

    <div class="row">

        <div class="col-md-12">

            <table class="table table-striped">

                <thead class="thead-inverse">
                    <tr>
                        <th>Nº Patromonio</th>
                        <th>Nome de Identificação</th>
                        <th>Descrição</th>
                        <th>Data de Compra</th>
                        <th></th>
                    </tr>
                </thead>

                <tbody>
                    <?php foreach ($this->view->ativos as $ativo){ ?>
                        <tr>
                        <!--<th scope='row'>--><?php //echo $ativo->ativo_id; ?><!--</th>-->
                            <td><?php echo $ativo->nrpatrimonio; ?></td>
                            <td><?php echo $ativo->nome; ?></td>
                            <td><?php echo $ativo->descricao; ?></td>
                            <td><?php echo date('d/m/Y',strtotime($ativo->datacompra)); ?></td>
                            <td class="text-right">

                                <a title="Clique para visualizar" href="ativo/visualizar/<?php echo $ativo->ativo_id; ?>" class="btn btn-outline-info">
                                    <i class="material-icons" style="font-size: 18px;">description</i>
                                    Detalhar
                                </a>

                                <a href="ativo/editar/<?php echo $ativo->ativo_id; ?>" class="btn btn-outline-primary" title="Clique para Editar">
                                    <i class="material-icons" style="font-size: 18px;">edit</i>
                                    Editar
                                </a>

                                <span onclick="global.confirmar('ativo/apagar/<?php echo $ativo->ativo_id; ?>', 'Apagar este ativo?')" class="btn btn-outline-danger" title="Clique para Apagar">
                                    <i class="material-icons" style="font-size: 18px;">delete</i>
                                    Apagar
                                </span>
                            </td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>

        </div>

    </div>

</div>