<div class="">
    <ul class="nav justify-content-center bg-light">
        <li class="nav-item">
            <a class="nav-link" href="/gerenciamento/ativo">
                <i class="material-icons">devices</i>
                Ativos
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/gerenciamento/categoriaativo">
                <i class="material-icons">devices_other</i>
                Categorias
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="/gerenciamento/sistemaoperacional">
                <i class="material-icons">settings_applications</i>
                Sistemas Operacionais
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="/gerenciamento/modelo">
                <i class="material-icons">cast</i>
                Modelos
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="/gerenciamento/fabricante">
                <i class="material-icons">developer_board</i>
                Fabricantes
            </a>
        </li>
    </ul>
</div>

<div class="container-fluid">

    <div class="row">

        <div class="col-md-4">
            <p>
                <h1>
                    <i class="material-icons" style="font-size: 38px">devices</i>
                    <?php $this->getPageTitle(); ?>
                </h1>
            </p>
        </div>

        <div class="col-md-8 text-right mt-3">
            <button type="button" class="btn btn-outline-primary" onclick="location='ativo/adicionar'">
                <i class="material-icons" style="font-size: 18px;">add</i>
                Criar Novo
            </button>
        </div>

    </div>

    <div class="row">

        <div class="col-md-12">

            <table class="table table-striped">

                <thead class="thead-inverse">
                    <tr>
                        <th>Nº Patromonio</th>
                        <th>Nome de Identificação</th>
                        <th>Descrição</th>
                        <th>Data de Compra</th>
                        <th></th>
                    </tr>
                </thead>

                <tbody>
                    <?php foreach ($this->view->ativos as $ativo){ ?>
                        <tr>
                            <td><?php echo $ativo->nrpatrimonio; ?></td>
                            <td><?php echo $ativo->nome; ?></td>
                            <td><?php echo $ativo->descricao; ?></td>
                            <td><?php echo date('d/m/Y',strtotime($ativo->datacompra)); ?></td>
                            <td class="text-right">

                                <a title="Clique para visualizar" href="ativo/visualizar/<?php echo $ativo->ativo_id; ?>" class="btn btn-outline-info">
                                    <i class="material-icons" style="font-size: 18px;">description</i>
                                    Detalhar
                                </a>

                                <a title="Clique para visualizar" href="ativo/manutencao/<?php echo $ativo->ativo_id; ?>" class="btn btn-outline-info">
                                    <i class="material-icons" style="font-size: 18px;">description</i>
                                    Detalhar
                                </a>

                                <a href="ativo/editar/<?php echo $ativo->ativo_id; ?>" class="btn btn-outline-primary" title="Clique para Editar">
                                    <i class="material-icons" style="font-size: 18px;">edit</i>
                                    Editar
                                </a>

                                <span onclick="global.confirmar('ativo/apagar/<?php echo $ativo->ativo_id; ?>', 'Apagar este ativo?')" class="btn btn-outline-danger" title="Clique para Apagar">
                                    <i class="material-icons" style="font-size: 18px;">delete</i>
                                    Apagar
                                </span>
                            </td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>

        </div>

    </div>

</div>