<div class="modal fade" id="msg" tabindex="-1" role="dialog" aria-labelledby="msgSuccess" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-danger text-white">
                <h4><?php echo $this->errors[0] ?></h4>
            </div>
            <div class="modal-body">
                <?php
                    for($i=1;$i<count($this->errors);$i++){
                        echo "<p>" . $this->errors[$i] . "<p>";
                    }
                ?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    jQuery('#msg').modal('show');
</script>