<script type="text/javascript" src="<?php echo BASE_URL ?>/public/js/dataTableAply.js"></script>

<div class="">
    <ul class="nav justify-content-center bg-light">
        <li class="nav-item">
            <a class="nav-link" href="ativo">
                <i class="material-icons">devices</i>
                Ativos
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="categoriaativo">
                <i class="material-icons">devices_other</i>
                Categorias
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="sistemaoperacional">
                <i class="material-icons">settings_applications</i>
                Sistemas Operacionais
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="modelo">
                <i class="material-icons">cast</i>
                Modelos
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="fabricante">
                <i class="material-icons">developer_board</i>
                Fabricantes
            </a>
        </li>
    </ul>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-8">
            <p>
            <h1>
                <i class="material-icons" style="font-size: 38px">devices_other</i>
                <?php echo $this->getPageTitle(); ?>
            </h1>
            </p>
        </div>
        <div class="col-md-4 text-right mt-3">
            <button type="button" class="btn btn-outline-primary" onclick="location='categoriaativo/adicionar'" title="Adicionar">
                <i class="material-icons" style="font-size: 18px;">add</i>
            </button>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <table id="table" class="table table-striped">
                <thead class="thead-inverse">
                <tr>
                    <th>Nome de Identificação</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($this->view->categoria_ativos as $categoria_ativo){ ?>
                    <tr>
                        <td><?php echo $categoria_ativo->nome; ?></td>
                        <td class="text-right">
                            <a href="categoriaativo/notificacao/<?php echo $categoria_ativo->id; ?>" class="btn btn-outline-info" title="Clique para escolher quem notificar">
                                <i class="material-icons" style="font-size: 18px;">notifications</i>
                            </a>
                            <a href="categoriaativo/editar/<?php echo $categoria_ativo->id; ?>" class="btn btn-outline-primary" title="Clique para Editar">
                                <i class="material-icons" style="font-size: 18px;">edit</i>
                            </a>
                            <span onclick="global.confirmar('categoriaativo/apagar/<?php echo $categoria_ativo->id; ?>', 'Apagar esta Categoria?')" class="btn btn-outline-danger" title="Clique para Apagar">
                                <i class="material-icons" style="font-size: 18px;">delete</i>
                            </span>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<?php
    if (isset($this->success))
        $this->setView('modal/success');
    else if (isset($this->errors))
        $this->setView('modal/error');