<!DOCTYPE html>

<html lang="pt-br">

    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="icon" href="/images/favicon.png" type="image/x-icon"/>
        <link rel="shortcut icon" href="/images/favicon.png" type="image/x-icon"/>

        <title> 404 Not Found | M&Mit</title>

        <!-- Bootstrap + Base-CSS -->
        <link href="/css/style-base.css" rel="stylesheet">

    </head>

    <body class="bg-dark" style="color:white">

        <div class="content">
            <div class="container ">
                <div class="row justify-content-md-center">
                    <div class="col-md-12">
                        <div class="error-template">
                            <h1>
                                Oops!</h1>
                            <h2>
                                404 Não Encontrada</h2>
                            <div class="error-details">
                                Desculpe, a requisição não foi encontrada!
                                Tem certeza que digitou certo?
                            </div>
                            <div class="error-actions">
                                <a onclick="history.go(-1)" class="btn btn-primary btn-lg">
                                    <i class="material-icons">arrow_back</i>
                                    Voltar
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </body>

    <footer class="footer">
        <div class="navbar navbar-dark bg-dark">
            <div class="row">
                <div class="col-md-12">
                    By @JMA
                </div>
            </div>
        </div>
    </footer>

</html>