<!DOCTYPE html>

<html lang="pt-br">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="icon" href="/images/favicon.png" type="image/x-icon"/>
    <link rel="shortcut icon" href="/images/favicon.png" type="image/x-icon"/>

    <title> Em Manutenção | M&Mit</title>

    <!-- Bootstrap + Base-CSS -->
    <link href="/css/style-base.css" rel="stylesheet">

</head>

<body class="bg-dark" style="color:white">

<div class="content">

    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="error-template">
                    <h1>
                        Oops!
                    </h1>
                    <h2>
                        Estamos temporariamente em manutanção</h2>
                    <h1>
                        Voltaremos logo!</h1>
                    <div>
                        <p>
                            Desculpe pelo inconveniente, mas estamos em manutanção no momento, estaremos operacionais logo!
                        </p>
                        <p>
                           - Equipe de Desenvolvimento
                        </p>
                    </div>
                    <div class="error-actions">
                        <a onclick="history.go(-1)" class="btn btn-primary btn-lg">
                            <i class="material-icons">arrow_back</i>
                            Voltar ao Inicio
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
<!--                <svg class="svg-box" width="380px" height="500px" viewbox="0 0 837 1045" version="1.1"-->
<!--                     xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"-->
<!--                     xmlns:sketch="http://www.bohemiancoding.com/sketch/ns">-->
<!--                    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" sketch:type="MSPage">-->
<!--                        <path d="M353,9 L626.664028,170 L626.664028,487 L353,642 L79.3359724,487 L79.3359724,170 L353,9 Z" id="Polygon-1" stroke="#3bafda" stroke-width="6" sketch:type="MSShapeGroup"></path>-->
<!--                        <path d="M78.5,529 L147,569.186414 L147,648.311216 L78.5,687 L10,648.311216 L10,569.186414 L78.5,529 Z" id="Polygon-2" stroke="#7266ba" stroke-width="6" sketch:type="MSShapeGroup"></path>-->
<!--                        <path d="M773,186 L827,217.538705 L827,279.636651 L773,310 L719,279.636651 L719,217.538705 L773,186 Z" id="Polygon-3" stroke="#f76397" stroke-width="6" sketch:type="MSShapeGroup"></path>-->
<!--                        <path d="M639,529 L773,607.846761 L773,763.091627 L639,839 L505,763.091627 L505,607.846761 L639,529 Z" id="Polygon-4" stroke="#00b19d" stroke-width="6" sketch:type="MSShapeGroup"></path>-->
<!--                        <path d="M281,801 L383,861.025276 L383,979.21169 L281,1037 L179,979.21169 L179,861.025276 L281,801 Z" id="Polygon-5" stroke="#ffaa00" stroke-width="6" sketch:type="MSShapeGroup"></path>-->
<!--                    </g>-->
<!--                </svg>-->
            </div>
        </div>
    </div>

</div>

</body>

<footer class="footer">
    <div class="navbar navbar-dark bg-dark">
        <div class="row">
            <div class="col-md-12">
                By @JMA
            </div>
        </div>
    </div>
</footer>

</html>