<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

    <a class="navbar-brand" style="color: #007bff" href="/">M&Mit</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="/">
                    <i class="material-icons">donut_large</i>
                    Dashboard
                </a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="/gerenciamento" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="material-icons">important_devices</i>
                    Gerenciamento
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="/gerenciamento/ativo">
                        <i class="material-icons">devices</i>
                        Ativos
                    </a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/monitoramento">
                    <i class="material-icons">track_changes</i>
                    Monitoramento
                </a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Digite sua Pesquisa" aria-label="Search">
            <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Pesquisar!</button>
        </form>
    </div>
</nav>
