<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

    <a class="navbar-brand" style="color: #007bff" href="/">
        M&Mit
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="/">
                    <i class="material-icons">donut_large</i>
                    Dashboard
                </a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="/gerenciamento" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="material-icons">important_devices</i>
                    Gerenciamento
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="/gerenciamento/ativo">
                        <i class="material-icons">devices</i>
                        Ativos
                    </a>
                    <a class="dropdown-item" href="/gerenciamento/componente">
                        <i class="material-icons">memory</i>
                        Componentes
                    </a>
                    <a class="dropdown-item" href="/gerenciamento/equipamento">
                        <i class="material-icons">keyboard</i>
                        Equipamentos
                    </a>
                    <a class="dropdown-item" href="/gerenciamento/licenca">
                        <i class="material-icons">copyright</i>
                        Licenças
                    </a>
                    <a class="dropdown-item" href="/gerenciamento/usuario">
                        <i class="material-icons">supervisor_account</i>
                        Usuários
                    </a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="/monitoramento" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="material-icons">track_changes</i>
                    Monitoramento
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="/monitoramento/internet">
                        <i class="material-icons">public</i>
                        Velocidade da Internet
                    </a>
                    <a class="dropdown-item" href="/monitoramento/icmp">
                        <i class="material-icons">drafts</i>
                        ICMP (Ping)
                    </a>
                    <a class="dropdown-item" href="/monitoramento/http">
                        <i class="material-icons">http</i>
                        HTTP/HTTPS
                    </a>
                    <a class="dropdown-item" href="/monitoramento/snmp">
                        <i class="material-icons">share</i>
                        SNMP
                    </a>
                </div>
            </li>
        </ul>
<!---->
<!--        <form class="form-inline">-->
<!--            <input class="form-control mr-sm-2" type="text" placeholder="Digite sua Pesquisa" aria-label="Search">-->
<!--            <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Pesquisar!</button>-->
<!--        </form>-->

        <ul class="navbar-nav text-left">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="/gerenciamento" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="material-icons" style="font-size: 22px;">account_circle</i>
                    <?php
                        echo $this->auth->name();
                    ?>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="/gerenciamento/usuario/mudarsenha">
                        <i class="material-icons" style="font-size: 22px">vpn_key</i>
                        Trocar Senha
                    </a>
                    <a class="dropdown-item" href="/gerenciamento/usuario/perfil">
                        <i class="material-icons" style="font-size: 22px">recent_actors</i>
                        Ver Perfil
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="/logout">
                        <i class="material-icons" style="font-size: 22px">forward</i>
                        Sair
                    </a>
                </div>
            </li>
        </ul>

    </div>
</nav>
