<div class="container-fluid mt-3">
    <div class="row">
        <div class="col-md-4">
            <p>
                <h1>
                    <i class="material-icons" style="font-size: 38px">settings</i>
                    <?php echo $this->getPageTitle(); ?>
                </h1>
            </p>
        </div>
        <div class="col-md-8 text-right mt-3">
            <button type="button" class="btn btn-outline-primary" title="Voltar" onclick="location='../internet'">
                <i class="material-icons" style="font-size: 18px;">arrow_back</i>
            </button>
        </div>
    </div>
    <form class="form-horizontal" action="<?php echo BASE_URL ?>/monitoramento/agendador/adicionar" method="post" accept-charset="utf-8">
        <input name="tipo" type="hidden" value="internet">
        <div class="card card-inverse">
            <div class="card-header">
                <div class="row">
                    <h3 class="col-md-10">
                        <i class="material-icons" style="font-size: 28px">history</i>
                        Agendamento de Disparos
                    </h3>
                </div>
            </div>
            <div class="card-body">
                <div class="form-group row">
                    <div class="col-md-2">
                        <label>Minuto</label>
                        <select class="form-control" name="minute">
                            <option value="*">*</option>
                            <?php for($i = 0; $i <= 60; $i++) { ?>
                            <option value="<?php echo $i ?>">
                                <?php echo $i; ?>
                            </option>
                            <?php } ?>
                        </select>
                    </div>
                    <div class="col-md-2">
                        <label>Hora</label>
                        <select class="form-control" name="hour">
                            <option value="*">*</option>
                            <?php for($i = 0; $i <= 24; $i++) { ?>
                            <option value="<?php echo $i ?>">
                                <?php echo $i; ?>
                            </option>
                            <?php } ?>
                        </select>
                    </div>
                    <div class="col-md-2">
                        <label>Dia</label>
                        <select class="form-control" name="day">
                            <option value="*">*</option>
                            <?php for($i = 1; $i <= 31; $i++) { ?>
                            <option value="<?php echo $i ?>">
                                <?php echo $i; ?>
                            </option>
                            <?php } ?>
                        </select>
                    </div>
                    <div class="col-md-2">
                        <label>Dia Semana</label>
                        <select class="form-control" name="week">
                            <option value="*">*</option>
                            <?php for($i = 1; $i <= 7; $i++) { ?>
                            <option value="<?php echo $i ?>">
                                <?php echo $i; ?>
                            </option>
                            <?php } ?>
                        </select>
                    </div>
                    <div class="col-md-2">
                        <label>Mês</label>
                        <select class="form-control" name="month">
                            <option value="*">*</option>
                            <?php for($i = 1; $i <= 12; $i++) { ?>
                            <option value="<?php echo $i ?>">
                                <?php echo $i; ?>
                            </option>
                            <?php } ?>
                        </select>
                    </div>
                    <div class="col-md-2">
                        <label class="text-white">T</label>
                        <button class="btn btn-success form-control">
                            <i class="material-icons" style="font-size: 18px;">schedule</i>
                            Agendar
                        </button>
                    </div>
                </div>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Períodicidade</th>
                            <th>Ultimo Disparo</th>
                            <th>Status</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->agendados as $a) { ?>
                        <tr>
                            <td>
                                <?php echo $a->minute . " " . $a->hour . " " . $a->day . " " . $a->month . " " . $a->week;?>
                            </td>
                            <td><?php echo date("d/m/Y H:i:s", strtotime($a->updated_at)) ?></td>
                            <td><?php echo $a->status ? "Habilitado" : "Desabilitado"; ?></td>
                            <td class="text-right">
                                <?php if ($a->status){ ?>
                                <button type='button' class='btn btn-outline-warning' onclick='location="../agendador/desativar/<?php echo $a->id; ?>"' title='Desabilitar'>
                                    <i class='material-icons' style='font-size: 18px;'>alarm_off</i>
                                </button>
                                <?php } else { ?>
                                <button type='button' class='btn btn-outline-success' onclick='location="../agendador/ativar/<?php echo $a->id; ?>"' title='Habilitar'>
                                    <i class='material-icons' style='font-size: 18px;'>alarm_on</i>
                                </button>
                                <?php } ?>
                                <button type='button' class='btn btn-outline-danger' onclick='global.confirmar("../agendador/remover/<?php echo $a->id; ?>","Tem certeza?")' title='Habilitar'>
                                    <i class='material-icons' style='font-size: 18px;'>close</i>
                                </button>
                            </td>
                        </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </form>
</div>

<?php
if (isset($this->success))
    $this->setView('modal/success');
else if (isset($this->errors))
    $this->setView('modal/error');