<div class="container-fluid mt-1">

    <form class="form-horizontal" action="/gerenciamento/sistemaoperacional/salvar" method="post" accept-charset="utf-8">
        <input name="action" type="hidden" value="<?php echo $this->view->action ?>">
        <input name="so_id" type="hidden" value="<?php echo $this->view->so->so_id ?>">

        <div class="card card-inverse">

            <div class="card-header">

                <div class="row">
                    <h3 class="col-md-10">
                        <i class="material-icons" style="font-size: 28px">settings_applications</i>
                        <?php echo $this->getPageTitle(); ?>
                    </h3>

                    <div class="col-md-2 text-right">
                        <button type="submit" class="btn btn-success">
                            <i class="material-icons" style="font-size: 18px;">done</i>
                            Gravar
                        </button>

                        <button type="button" class="btn btn-danger" onclick="history.go(-1)">
                            <i class="material-icons" style="font-size: 18px;">clear</i>
                            Cancelar
                        </button>
                    </div>
                </div>
            </div>

            <div class="card-body">

                <div class="form-group">
                    <label>Nome do Sistema Operacional</label>
                    <input required name="nome" class="form-control" placeholder=""
                           value="<?php echo $this->view->so->nome ?>">
                </div>

                <div class="form-group">
                    <label>Versão</label>
                    <input name="versao" class="form-control" placeholder=""
                           value="<?php echo $this->view->so->versao ?>">
                </div>

            </div>

        </div>

    </form>

</div>