<div class="container-fluid mt-1">

    <form class="form-horizontal" action="/gerenciamento/modelo/salvar" method="post" accept-charset="utf-8">
        <input name="action" type="hidden" value="<?php echo $this->view->action ?>">
        <input name="id" type="hidden" value="<?php echo $this->view->modelo->id ?>">

        <div class="card card-inverse">

            <div class="card-header">

                <div class="row">
                    <h3 class="col-md-10">
                        <i class="material-icons" style="font-size: 28px">cast</i>
                        <?php echo $this->getPageTitle(); ?>
                    </h3>

                    <div class="col-md-2 text-right">
                        <button type="submit" class="btn btn-success">
                            <i class="material-icons" style="font-size: 18px;">done</i>
                            Gravar
                        </button>

                        <button type="button" class="btn btn-danger" onclick="history.go(-1)">
                            <i class="material-icons" style="font-size: 18px;">clear</i>
                            Cancelar
                        </button>
                    </div>
                </div>
            </div>

            <div class="card-body">

                <div class="form-group">
                    <label>Nome da Modelo</label>
                    <input required name="nome" class="form-control" placeholder=""
                           value="<?php echo $this->view->modelo->nome ?>">
                </div>

                <div class="form-group">
                    <label>Fabricante</label>
                    <select  class="form-control" name="fabricante_id">

                        <?php

                        $selected = "";

                        foreach ($this->view->fabricante as $fabricante) {
                            if (isset($this->view->modelo->fabricante_id) && ($fabricante->id == $this->view->modelo->fabricante_id)) {
                                $selected = "selected";
                            }
                            else{
                                $selected = "";
                            }
                            ?>
                            <option <?php echo $selected ?> value="<?php echo $fabricante->id?>">
                                <?php echo $fabricante->nome?>
                            </option>

                        <?php } ?>

                    </select>
                </div>

            </div>

        </div>

    </form>

</div>