<div class="container-fluid mt-3">
    <form class="form-horizontal" action="<?php echo BASE_URL ?>/gerenciamento/categoriacomponente/salvar" method="post" accept-charset="utf-8">
        <input name="action" type="hidden" value="<?php echo $this->view->action ?>">
        <input name="id" type="hidden" value="<?php echo $this->view->categoria->id ?>">
        <div class="card card-inverse">
            <div class="card-header">
                <div class="row">
                    <h3 class="col-md-8">
                        <i class="material-icons" style="font-size: 28px">save</i>
                        <?php echo $this->getPageTitle(); ?>
                    </h3>
                    <div class="col-md-4 text-right">
                        <button type="submit" class="btn btn-outline-success">
                            <i class="material-icons" style="font-size: 18px;">done</i>
                            Gravar
                        </button>
                        <button type="button" class="btn btn-outline-danger" onclick="history.go(-1)">
                            <i class="material-icons" style="font-size: 18px;">clear</i>
                            Cancelar
                        </button>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="form-group">
                    <label>Nome da Categoria</label>
                    <input name="nome" class="form-control" placeholder="Nome Identificador" required
                           value="<?php echo $this->view->categoria->nome ?>">
                </div>
                <div class="form-group">
                    <label>Unidade de Valor</label>
                    <input name="tipo_valor" class="form-control" placeholder="GigaBytes, GigaHertz, etc..."
                           value="<?php echo $this->view->categoria->tipo_valor ?>">
                </div>
                <div class="form-group">
                    <label>Sigla da Unidade</label>
                    <input name="sigla_valor" class="form-control" placeholder="GB, GHz, etc..."
                            value="<?php echo $this->view->categoria->sigla_valor ?>">
                </div>
            </div>
        </div>
    </form>
</div>