<script type="text/javascript" src="/js/dataTableAply.js"></script>

<div class="">
    <ul class="nav justify-content-center bg-light">
        <li class="nav-item">
            <a class="nav-link" href="/gerenciamento/componente">
                <i class="material-icons">memory</i>
                Componentes
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/gerenciamento/categoriacomponente">
                <i class="material-icons">save</i>
                Categorias
            </a>
        </li>
        <!--        <li class="nav-item">-->
        <!--            <a class="nav-link " href="/gerenciamento/modelo">-->
        <!--                <i class="material-icons">cast</i>-->
        <!--                Modelos-->
        <!--            </a>-->
        <!--        </li>-->
        <!--        <li class="nav-item">-->
        <!--            <a class="nav-link " href="/gerenciamento/fabricante">-->
        <!--                <i class="material-icons">developer_board</i>-->
        <!--                Fabricantes-->
        <!--            </a>-->
        <!--        </li>-->
    </ul>
</div>

<div class="container-fluid">

    <div class="row">

        <div class="col-md-6">
            <p>
            <h1>
                <i class="material-icons" style="font-size: 38px">save</i>
                <?php $this->getPageTitle(); ?>
            </h1>
            </p>
        </div>

        <div class="col-md-6 text-right mt-3">
            <button type="button" class="btn btn-outline-primary" onclick="location='categoriacomponente/adicionar'" title="Adicionar">
                <i class="material-icons" style="font-size: 18px;">add</i>
            </button>
        </div>

    </div>

    <div class="row">

        <div class="col-md-12">

            <table id="table" class="table table-striped">

                <thead class="thead-inverse">
                <tr>
                    <th>Nome de Identificação</th>
                    <th>Unidade de Valor</th>
                    <th>Sigla da Unidade</th>
                    <th></th>
                </tr>
                </thead>

                <tbody>
                <?php foreach ($this->view->categorias as $categoria){ ?>
                    <tr>
                        <td><?php echo $categoria->nome; ?></td>
                        <td><?php echo $categoria->tipo_valor; ?></td>
                        <td><?php echo $categoria->sigla_valor; ?></td>
                        <td class="text-right">

                            <a href="categoriacomponente/editar/<?php echo $categoria->categoria_componente_id; ?>" class="btn btn-outline-primary" title="Clique para Editar">
                                <i class="material-icons" style="font-size: 18px;">edit</i>
                            </a>

                            <span onclick="global.confirmar('categoriacomponente/apagar/<?php echo $categoria->categoria_componente_id; ?>', 'Apagar esta Categoria?')" class="btn btn-outline-danger" title="Clique para Apagar">
                                <i class="material-icons" style="font-size: 18px;">delete</i>
                            </span>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>

        </div>

    </div>

</div>