<script type="text/javascript" src="<?php echo BASE_URL ?>/public/js/dataTableAply.js"></script>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-10">
            <p>
                <h1>
                    <i class="material-icons" style="font-size: 38px">drafts</i>
                    <?php echo $this->getPageTitle(); ?>
                </h1>
            </p>
        </div>
        <?php if ($this->auth->type()) { ?>
        <div class="col-md-2 text-right mt-3">
            <button type="button" class="btn btn-outline-primary" title="run" onclick="location='icmp/run'">
                <i class="material-icons" style="font-size: 18px;">play_arrow</i>
            </button>
            <button type="button" class="btn btn-outline-dark" title="Configurações" onclick="location='icmp/config'">
                <i class="material-icons" style="font-size: 18px;">settings</i>
            </button>
        </div>
        <?php } ?>
    </div>
    <div class="row">
        <div class="col-12 text-center">
            <h2> <i class="material-icons" style="font-size: 32px;">history</i> Execuções mais recentes...</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <table id="table" class="table table-striped">
                <thead class="thead-inverse">
                    <tr>
                        <th class="text-center">Status</th>
                        <th>Nome do Ativo</th>
                        <th>IP - Interface de Rede</th>
                        <th>Execução</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($this->view->pings as $ping) {
                    if(!empty($ping->created_at)) {?>
                    <tr>
                        <td class="text-center">
                            <?php
                            echo "<i class='material-icons";
                            echo $ping->status == 0 ? " text-success' title='Acessível'>check" : " text-danger' title='Inacessível'>clear";
                            echo "</i>";
                            ?>
                        </td>
                        <td><?php echo $ping->interface_rede->ativo->nome; ?></td>
                        <td><?php echo $ping->interface_rede->ip; ?></td>
                        <td><?php echo date('d/m/Y H:i:s',strtotime($ping->updated_at)); ?></td>
                        <td class="text-right">
                            <span onclick="showModal(<?php echo $ping->interface_rede_id; ?>)" class="btn btn-outline-primary" title="Resultado Completo">
                                <i class="material-icons" style="font-size: 18px;">more_horiz</i>
                            </span>
                        </td>
                    </tr>
                    <div class="modal fade" id="<?php echo $ping->interface_rede_id; ?>" tabindex="-1" role="dialog" aria-labelledby="msgSuccess" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header bg-primary text-white">
                                    <h4>Detalhes da Execução</h4>
                                </div>
                                <div class="modal-body">
                                    <?php echo $ping->descricao; ?>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <script type="text/javascript">
                        function showModal(id)
                        {
                            jQuery("#"+id).modal('show');
                        }
                    </script>
                <?php }} ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<?php
    if (isset($this->success))
        $this->setView('modal/success');
    else if (isset($this->errors))
        $this->setView('modal/error');