<script type="text/javascript" src="/js/dataTableAply.js"></script>

<div class="">
    <ul class="nav justify-content-center bg-light">
        <li class="nav-item">
            <a class="nav-link" href="/gerenciamento/ativo">
                <i class="material-icons">devices</i>
                Ativos
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/gerenciamento/categoriaativo">
                <i class="material-icons">devices_other</i>
                Categorias
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="/gerenciamento/sistemaoperacional">
                <i class="material-icons">settings_applications</i>
                Sistemas Operacionais
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="/gerenciamento/modelo">
                <i class="material-icons">cast</i>
                Modelos
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="/gerenciamento/fabricante">
                <i class="material-icons">developer_board</i>
                Fabricantes
            </a>
        </li>
    </ul>
</div>

<div class="container-fluid">

    <div class="row">

        <div class="col-md-4">
            <p>
            <h1>
                <i class="material-icons" style="font-size: 38px">developer_board</i>
                <?php $this->getPageTitle(); ?>
            </h1>
            </p>
        </div>

        <div class="col-md-8 text-right mt-3">
            <button type="button" class="btn btn-outline-primary" onclick="location='fabricante/adicionar'" title="Adicionar">
                <i class="material-icons" style="font-size: 18px;">add</i>
            </button>
        </div>

    </div>

    <div class="row">

        <div class="col-md-12">

            <table id="table" class="table table-striped">

                <thead class="thead-inverse">
                <tr>
                    <th>Nome de Identificação</th>
                    <th></th>
                </tr>
                </thead>

                <tbody>
                <?php foreach ($this->view->fabricantes as $fabricante){ ?>
                    <tr>
                        <td><?php echo $fabricante->nome; ?></td>
                        <td class="text-right">

                            <a href="fabricante/editar/<?php echo $fabricante->fabricante_id; ?>" class="btn btn-outline-primary" title="Clique para Editar">
                                <i class="material-icons" style="font-size: 18px;">edit</i>
                            </a>

                            <span onclick="global.confirmar('fabricante/apagar/<?php echo $fabricante->fabricante_id; ?>', 'Apagar este Fabricante?')" class="btn btn-outline-danger" title="Clique para Apagar">
                                <i class="material-icons" style="font-size: 18px;">delete</i>
                            </span>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>

        </div>

    </div>

</div>