<script type="text/javascript" src="<?php echo BASE_URL ?>/public/js/dataTableAply.js"></script>

<ul class="nav justify-content-center bg-light">
    <li class="nav-item">
        <a class="nav-link" href="usuario">
            <i class="material-icons">person</i>
            Usuários
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="grupo">
            <i class="material-icons">people</i>
            Grupos
        </a>
    </li>
</ul>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-10">
            <p>
                <h1>
                    <i class="material-icons" style="font-size: 38px">person</i>
                    <?php echo $this->getPageTitle(); ?>
                </h1>
            </p>
        </div>
        <div class="col-md-2 text-right mt-3">
            <button type="button" class="btn btn-outline-primary" onclick="location='usuario/adicionar'" title="Adicionar">
                <i class="material-icons" style="font-size: 18px;">add</i>
            </button>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <table id="table" class="table table-striped">
                <thead class="thead-inverse">
                    <tr>
                        <th>Nome de Usuário</th>
                        <th>Email</th>
                        <th>Grupo</th>
                        <th>Tipo</th>
                        <th>Criado em</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($this->view->usuarios as $usuario){ ?>
                    <tr>
                        <td><?php echo $usuario->name; ?></td>
                        <td><?php echo $usuario->email; ?></td>
                        <td><?php echo $usuario->grupo->nome; ?></td>
                        <td><?php echo $usuario->type ? "Administrador" : "Usuário Comum"; ?></td>
                        <td><?php echo date('d/m/Y H:i:s', strtotime($usuario->created_at)) ?></td>
                        <td class="text-right">
                            <a href="usuario/editar/<?php echo $usuario->id; ?>" class="btn btn-outline-primary" title="Clique para Editar">
                                <i class="material-icons" style="font-size: 18px;">edit</i>
                            </a>
                            <span onclick="global.confirmar('usuario/apagar/<?php echo $usuario->id; ?>', 'Apagar este Usuário?')" class="btn btn-outline-danger" title="Clique para Apagar">
                                <i class="material-icons" style="font-size: 18px;">delete</i>
                            </span>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<?php
    if (isset($this->success))
        $this->setView('modal/success');
    else if (isset($this->errors))
        $this->setView('modal/error');