<!--<script type="text/javascript" src="/js/dataTableAply.js"></script>-->
<link href="/css/usuario/perfil.css" rel="stylesheet">

<div class="container-fluid">

    <div class="row">

        <div class="col-md-12 border-bottom-1">
            <p>
                <i class="material-icons perfil-icon">account_circle</i>
            <h1 class="float-right">
                <?php echo $this->getPageTitle(); ?>
            </h1>
            </p>
        </div>

    </div>

    <br><br>

    <div class="row">

        <div class="col-md-12">
            <h2>Ativos em sua Responsabilidade</h2>
            <table id="table" class="table table-striped">

                <thead class="thead-inverse">
                <tr>
                    <th>Nome do Grupo</th>
                    <th>Atribuido em</th>
                </tr>
                </thead>

                <tbody>
                <?php foreach ($this->view->ativos as $ativo){ ?>
                    <tr>
                        <td><?php echo $ativo->nome; ?></td>
                        <td><?php echo date('d/m/Y H:i:s', strtotime($ativo->created_at)) ?></td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>

        </div>

    </div>

</div>

<?php

if (isset($this->success)){
    $this->setView('modal/success');
}
else if (isset($this->errors)){
    $this->setView('modal/error');
}

?>