<script type="text/javascript" src="<?php echo BASE_URL ?>/public/js/dataTableAply.js"></script>
<div class="menu-barra">
    <ul class="nav justify-content-center bg-light">
        <li class="nav-item">
            <a class="nav-link" href="snmp">
                <i class="material-icons">share</i>
                Monitoramento
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="oid">
                <i class="material-icons">casino</i>
                Coleção de OID's
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="oid-ativo">
                <i class="material-icons">compare_arrows</i>
                Relacionar
            </a>
        </li>
    </ul>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-10">
            <p>
                <h1>
                    <i class="material-icons" style="font-size: 38px">share</i>
                    <?php echo $this->getPageTitle(); ?>
                </h1>
            </p>
        </div>
        <div class="col-md-2 text-right mt-3">
            <button type="button" class="btn btn-outline-primary" title="run" onclick="location='snmp/run'">
                <i class="material-icons" style="font-size: 18px;">play_arrow</i>
            </button>
            <button type="button" class="btn btn-outline-dark" title="Configurações" onclick="location='snmp/config'">
                <i class="material-icons" style="font-size: 18px;">settings</i>
            </button>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <table id="table" class="table table-striped">
                <thead class="thead-inverse">
                    <tr>
                        <th>Nome do Ativo</th>
                        <th>OID</th>
                        <th>Valor</th>
                        <th>Execução</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($this->view->snmps as $snmp) {
                    if(!empty($snmp->created_at)) {?>
                        <tr>
                            <td><?php echo $snmp->ativo->nome; ?></td>
                            <td><?php echo $snmp->oid->nome; ?></td>
                            <td><?php echo $snmp->valor; ?></td>
                            <td><?php echo date('d/m/Y H:i:s',strtotime($snmp->updated_at)); ?></td>
                        </tr>
                    <?php }} ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<?php
    if (isset($this->success))
        $this->setView('modal/success');
    else if (isset($this->errors))
        $this->setView('modal/error');