<div class="container-fluid mt-1">

    <form class="form-horizontal" action="/gerenciamento/categoriaequipamento/salvar" method="post" accept-charset="utf-8">
        <input name="action" type="hidden" value="<?php echo $this->view->action ?>">
        <input name="categoria_equipamento_id" type="hidden" value="<?php echo $this->view->categoria->categoria_equipamento_id ?>">

        <div class="card card-inverse">

            <div class="card-header">

                <div class="row">
                    <h3 class="col-md-10">
                        <i class="material-icons" style="font-size: 28px">mouse</i>
                        <?php echo $this->getPageTitle(); ?>
                    </h3>

                    <div class="col-md-2 text-right">
                        <button type="submit" class="btn btn-success">
                            <i class="material-icons" style="font-size: 18px;">done</i>
                            Gravar
                        </button>

                        <button type="button" class="btn btn-danger" onclick="location='/gerenciamento/categoriaequipamento'">
                            <i class="material-icons" style="font-size: 18px;">clear</i>
                            Cancelar
                        </button>
                    </div>
                </div>
            </div>

            <div class="card-body">

                <div class="form-group">
                    <label>Nome</label>
                    <input name="nome" type="text" class="form-control" placeholder="Nome Visível"
                           value="<?php
                                    echo isset($this->inputs['nome']) ? $this->inputs['nome'] : $this->view->categoria->nome
                                ?>">
                    <?php if (isset($this->errors['nome'])) { ?>
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <?php echo $this->errors['nome'];?>
                        </div>
                    <?php } ?>


                </div>

            </div>

        </div>

    </form>

</div>
