<div class="container-fluid mt-1">

    <form class="form-horizontal" action="/gerenciamento/licenca/salvar" method="post" accept-charset="utf-8">
        <input name="action" type="hidden" value="<?php echo $this->view->action ?>">
        <input name="licenca_id" type="hidden" value="<?php echo $this->view->licenca->licenca_id ?>">

        <div class="card card-inverse">

            <div class="card-header">

                <div class="row">
                    <h3 class="col-md-10">
                        <i class="material-icons" style="font-size: 28px">copyright</i>
                        <?php echo $this->getPageTitle(); ?>
                    </h3>

                    <div class="col-md-2 text-right">
                        <button type="submit" class="btn btn-outline-success">
                            <i class="material-icons" style="font-size: 18px;">done</i>
                            Gravar
                        </button>

                        <button type="button" class="btn btn-outline-danger" onclick="history.go(-1)">
                            <i class="material-icons" style="font-size: 18px;">clear</i>
                            Cancelar
                        </button>
                    </div>
                </div>
            </div>

            <div class="card-body">

                <div class="form-group">
                    <label>Nome</label>
                    <input name="nome" class="form-control" placeholder="Nome Identificador"
                           value="<?php echo $this->view->licenca->nome?>">
                </div>
                <div class="form-group">
                    <label>Serial</label>
                    <input name="serial" class="form-control" placeholder="Serial ou Chave de Ativação"
                           value="<?php echo $this->view->licenca->serial?>">
                </div>
                <div class="form-group">
                    <label>Data de Aquisição</label>
                    <input name="datacompra" class="form-control" type="date"
                           value="<?php echo $this->view->licenca->datacompra?>">
                </div>
                <div class="form-group">
                    <label>Data de Expiração</label>
                    <input name="datavence" class="form-control" type="date"
                           value="<?php echo $this->view->licenca->datavence?>">
                </div>
                <div class="form-group">
                    <label>Categoria</label>
                    <select  class="form-control" name="categoria_licenca_id">

                        <?php

                        $selected = "";

                        foreach ($this->view->categorias as $categoria) {
                            if (isset($this->view->licenca->categoria_licenca_id) && ($categoria->categoria_licenca_id == $this->view->licenca->categoria_licenca_id)) {
                                $selected = "selected";
                            }
                            else{
                                $selected = "";
                            }
                            ?>
                            <option <?php echo $selected ?> value="<?php echo $categoria->categoria_licenca_id?>">
                                <?php echo $categoria->nome ?>
                            </option>

                        <?php } ?>

                    </select>
                </div>

            </div>

        </div>

    </form>

</div>