<script type="text/javascript" src="/js/dataTableAply.js"></script>

<div class="">
    <ul class="nav justify-content-center bg-light">
        <li class="nav-item">
            <a class="nav-link" href="/gerenciamento/componente">
                <i class="material-icons">memory</i>
                Componentes
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/gerenciamento/categoriacomponente">
                <i class="material-icons">save</i>
                Categorias
            </a>
        </li>
<!--        <li class="nav-item">-->
<!--            <a class="nav-link " href="/gerenciamento/modelo">-->
<!--                <i class="material-icons">cast</i>-->
<!--                Modelos-->
<!--            </a>-->
<!--        </li>-->
<!--        <li class="nav-item">-->
<!--            <a class="nav-link " href="/gerenciamento/fabricante">-->
<!--                <i class="material-icons">developer_board</i>-->
<!--                Fabricantes-->
<!--            </a>-->
<!--        </li>-->
    </ul>
</div>

<div class="container-fluid">

    <div class="row">

        <div class="col-md-4">
            <p>
            <h1>
                <i class="material-icons" style="font-size: 38px">memory</i>
                <?php $this->getPageTitle(); ?>
            </h1>
            </p>
        </div>

        <div class="col-md-8 text-right mt-3">
            <button type="button" class="btn btn-outline-primary" onclick="location='componente/adicionar'" title="Adicionar">
                <i class="material-icons" style="font-size: 18px;">add</i>
            </button>
        </div>

    </div>

    <div class="row">

        <div class="col-md-12">

            <table id="table" class="table table-striped">

                <thead class="thead-inverse">
                <tr>
                    <th>Nome de Identificação</th>
                    <th>Valor</th>
                    <th>Categoria</th>
                    <th>Ativo</th>
                    <th></th>
                </tr>
                </thead>

                <tbody>
                <?php foreach ($this->view->componentes as $componente){ ?>
                    <tr>
                        <td><?php echo $componente->nome; ?></td>
                        <td><?php echo $componente->valor . $componente->sigla_valor; ?></td>
                        <td><?php echo $componente->categoria; ?></td>
                        <td><?php echo isset($componente->ativo) ? $componente->ativo : "Não atribuído" ?></td>
                        <td class="text-right">

                            <a href="componente/editar/<?php echo $componente->componente_id; ?>" class="btn btn-outline-primary" title="Clique para Editar">
                                <i class="material-icons" style="font-size: 18px;">edit</i>
                            </a>

                            <span onclick="global.confirmar('componente/apagar/<?php echo $componente->componente_id; ?>', 'Apagar este Componente?')" class="btn btn-outline-danger" title="Clique para Apagar">
                                <i class="material-icons" style="font-size: 18px;">delete</i>
                            </span>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>

        </div>

    </div>

</div>