<script type="text/javascript" src="<?php echo BASE_URL ?>/public/js/dataTableAply.js"></script>
<div class="container-fluid">
    <div class="row mb-2">
        <div class="col-md-10">
            <p>
                <h1>
                    <i class="material-icons" style="font-size: 38px">language</i>
                    <?php echo $this->getPageTitle(); ?>
                </h1>
            </p>
        </div>
        <div class="col-md-2 text-right mt-3">
            <button type="button" class="btn btn-outline-primary" onclick="location='../ativo" title="Voltar">
                <i class="material-icons" style="font-size: 18px;">arrow_back</i>
            </button>
            <button type="button" class="btn btn-outline-primary"  onclick="location='../adicionar/<?php echo $this->view->ativo->id ?>'" title="Criar Nova">
                <i class="material-icons" style="font-size: 18px;">add</i>
            </button>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <table id="table" class="table table-striped">
                <thead class="thead-inverse">
                    <tr>
                        <th>Hostname</th>
                        <th>IP</th>
                        <th>Mascara</th>
                        <th>GateWay</th>
                        <th>DNS 1</th>
                        <th>DNS 2</th>
                        <th>Mac Address</th>
                        <th class="text-center">Monitorada</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($this->view->interfaces as $interface){ ?>
                    <tr>
                        <td><?php echo $interface->hostname; ?></td>
                        <td><?php echo $interface->ip; ?></td>
                        <td><?php echo $interface->mascara; ?></td>
                        <td><?php echo $interface->gateway; ?></td>
                        <td><?php echo $interface->dns1; ?></td>
                        <td><?php echo $interface->dns2; ?></td>
                        <td><?php echo $interface->macaddress; ?></td>
                        <td class="text-center">
                            <?php
                            echo "<i class='material-icons";
                            echo $interface->monitorar == 1 ? " text-success' title='Sim'>check" : " text-danger' title='Não'>clear";
                            echo "</i>";
                            ?>
                        </td>
                        <td class="text-right">
                            <a href="../editar/<?php echo $interface->id; ?>" class="btn btn-outline-primary" title="Clique para Editar">
                                <i class="material-icons" style="font-size: 18px;">edit</i>
                            </a>
                            <span onclick="global.confirmar('../apagar/<?php echo $this->view->ativo->id?>/<?php echo $interface->id ?>', 'Apagar esta Interface?')" class="btn btn-outline-danger" title="Clique para Apagar">
                                <i class="material-icons" style="font-size: 18px;">delete</i>
                            </span>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<?php

    if (isset($this->success))
        $this->setView('modal/success');
    else if (isset($this->errors))
        $this->setView('modal/error');