<div class="container-fluid mt-1">

    <form class="form-horizontal" action="/gerenciamento/categorialicenca/salvar" method="post" accept-charset="utf-8">
        <input name="action" type="hidden" value="<?php echo $this->view->action ?>">
        <input name="categoria_licenca_id" type="hidden" value="<?php echo $this->view->categoria->categoria_licenca_id ?>">

        <div class="card card-inverse">

            <div class="card-header">

                <div class="row">
                    <h3 class="col-md-10">
                        <i class="material-icons" style="font-size: 28px">class</i>
                        <?php echo $this->getPageTitle(); ?>
                    </h3>

                    <div class="col-md-2 text-right">
                        <button type="submit" class="btn btn-outline-success">
                            <i class="material-icons" style="font-size: 18px;">done</i>
                            Gravar
                        </button>

                        <button type="button" class="btn btn-outline-danger" onclick="history.go(-1)">
                            <i class="material-icons" style="font-size: 18px;">clear</i>
                            Cancelar
                        </button>
                    </div>
                </div>
            </div>

            <div class="card-body">

                <div class="form-group">
                    <label>Nome</label>
                    <input name="nome" class="form-control" placeholder="Nome Completo da Categoria"
                           value="<?php echo $this->view->categoria->nome?>">
                </div>
                <div class="form-group">
                    <label>Sigla</label>
                    <input name="sigla" class="form-control" placeholder="Sigla para Exibição"
                           value="<?php echo $this->view->categoria->sigla?>">
                </div>

            </div>

        </div>

    </form>

</div>