<script type="text/javascript" src="<?php echo BASE_URL ?>/public/js/dataTableAply.js"></script>

<div class="">
    <ul class="nav justify-content-center bg-light">
        <li class="nav-item">
            <a class="nav-link" href="licenca">
                <i class="material-icons">copyright</i>
                Licenças
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="categorialicenca">
                <i class="material-icons">class</i>
                Categorias
            </a>
        </li>
    </ul>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-10">
            <p>
                <h1>
                    <i class="material-icons" style="font-size: 38px">class</i>
                    <?php echo $this->getPageTitle(); ?>
                </h1>
            </p>
        </div>
        <div class="col-md-2 text-right mt-3">
            <button type="button" class="btn btn-outline-primary" title="Adicionar" onclick="location='categorialicenca/adicionar'">
                <i class="material-icons" style="font-size: 18px;">add</i>
            </button>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <table id="table" class="table table-striped">
                <thead class="thead-inverse">
                <tr>
                    <th>Nome de Identificação</th>
                    <th>Sigla de Exibição</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($this->view->categorias as $categoria){ ?>
                    <tr>
                        <td><?php echo $categoria->nome; ?></td>
                        <td><?php echo $categoria->sigla; ?></td>
                        <td class="text-right">
                            <a href="categorialicenca/editar/<?php echo $categoria->id; ?>" class="btn btn-outline-primary" title="Clique para Editar">
                                <i class="material-icons" style="font-size: 18px;">edit</i>
                            </a>
                            <span onclick="global.confirmar('categorialicenca/apagar/<?php echo $categoria->id; ?>', 'Apagar esta Categoria?')" class="btn btn-outline-danger" title="Clique para Apagar">
                                <i class="material-icons" style="font-size: 18px;">delete</i>
                            </span>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<?php
    if (isset($this->success))
        $this->setView('modal/success');
    else if (isset($this->errors))
        $this->setView('modal/error');